int bitAnd(int, int);
int test_bitAnd(int, int);
int copyLSB(int);
int test_copyLSB(int);
int getByte(int, int);
int test_getByte(int, int);
int isEqual(int, int);
int test_isEqual(int, int);
int bitMask(int, int);
int test_bitMask(int, int);
int reverseBytes(int);
int test_reverseBytes(int);
int bang(int);
int test_bang(int);
int leastBitPos(int);
int test_leastBitPos(int);
int minusOne();
int test_minusOne();
int tmax();
int test_tmax();
int fitsBits(int, int);
int test_fitsBits(int, int);
int addOK(int, int);
int test_addOK(int, int);
int isGreater(int, int);
int test_isGreater(int, int);
int isNegative(int);
int test_isNegative(int);
int multFiveEighths(int);
int test_multFiveEighths(int);
int sm2tc(int);
int test_sm2tc(int);
unsigned float_i2f(int);
unsigned test_float_i2f(int);
